name: 'dos-pascal-docker'
description: 'Compile Turbo Pascal for DOS'
inputs:
  path:
    description: 'Path for main pascal file e.g. "src/MAIN.PAS"'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/adam-zielonka/dos-pascal-docker:main'
  args:
    - ${{ inputs.path }}
